################################################################################
# Ansible Inventory Generation
# Generates hosts.yml, group_vars, and helper files
################################################################################

# =============================================================================
# Local Values for Inventory
# =============================================================================

locals {
  # Extract public IPs from IPAM reservations
  public_ips = [for ip in scaleway_ipam_ip.public_ips : ip.address]
  
  # Extract cluster IPs from IPAM reservations
  cluster_ips = [for ip in scaleway_ipam_ip.cluster_ips : ip.address]
  
  # Extract public IPv4 addresses from servers (Scaleway public IPs for SSH)
  server_public_ipv4 = [
    for server in scaleway_baremetal_server.nodes : 
    [for ip in server.ipv4 : ip.address][0]
  ]
  
  # Alias for outputs compatibility
  server_ssh_ips = local.server_public_ipv4
  
  # Extract VLAN IDs from server private networks
  # Note: Scaleway assigns different VLANs per physical rack
  server_vlans = [
    for server in scaleway_baremetal_server.nodes : {
      public_vlan  = [for pn in server.private_network : pn.vlan if pn.id == scaleway_vpc_private_network.public.id]
      cluster_vlan = [for pn in server.private_network : pn.vlan if pn.id == scaleway_vpc_private_network.cluster.id]
    }
  ]
}

# =============================================================================
# Ansible Inventory (hosts.yml)
# =============================================================================

resource "local_file" "ansible_inventory" {
  count = var.generate_inventory ? 1 : 0

  depends_on = [scaleway_baremetal_server.nodes]

  filename = "${path.root}/../ansible/inventory/hosts.yml"
  content  = <<-EOF
---
# Generated by Terraform - ${timestamp()}
# Ansible inventory for Proxmox Ceph HCI cluster
#
# IMPORTANT: VLAN IDs are assigned per physical rack by Scaleway.
# Different servers may have different VLAN IDs even on the same Private Network.

all:
  children:
    proxmox:
      hosts:
%{for i, server in scaleway_baremetal_server.nodes~}
        ${server.name}:
          # Connection
          ansible_host: ${local.server_public_ipv4[i]}
          
          # Private Network IPs (for Ceph/cluster)
          pve_cluster_addr0: ${local.public_ips[i]}
          pve_cluster_addr1: ${local.cluster_ips[i]}
          
          # VLAN IDs (per-host - assigned by Scaleway based on rack)
          public_vlan: ${local.server_vlans[i].public_vlan[0]}
          cluster_vlan: ${local.server_vlans[i].cluster_vlan[0]}
          
          # Ceph OSD devices
          ceph_osd_devices: ${jsonencode(local.ceph_osd_disks)}
%{endfor~}
%{if var.enable_qdevice~}
        ${var.cluster_name}-qdevice:
          ansible_host: ${scaleway_instance_server.qdevice[0].private_ips[0].address}
          role: qdevice
%{endif~}

      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
EOF

  lifecycle {
    ignore_changes = [content]
  }
}

# =============================================================================
# Ansible Group Variables
# =============================================================================

resource "local_file" "ansible_group_vars" {
  count = var.generate_inventory ? 1 : 0

  depends_on = [scaleway_baremetal_server.nodes]

  filename = "${path.root}/../ansible/inventory/group_vars/proxmox.yml"
  content  = <<-EOF
---
# Generated by Terraform - ${timestamp()}
# Group variables for Proxmox cluster

# =============================================================================
# Proxmox Cluster Configuration
# =============================================================================
pve_group: proxmox
pve_cluster_enabled: true
pve_cluster_clustername: ${var.cluster_name}

pve_reboot_on_kernel_update: false
pve_repository_line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
pve_remove_subscription_warning: true

# Service password for cluster join (sensitive)
service_password: "${var.service_password}"

pve_extra_packages:
  - ifupdown2
  - vim
  - htop

# =============================================================================
# Network Configuration
# =============================================================================
public_network: "${var.public_network_subnet}"
cluster_network: "${var.cluster_network_subnet}"

# NOTE: VLAN IDs are defined per-host in hosts.yml
# Scaleway Elastic Metal assigns different VLANs per physical rack

# =============================================================================
# Ceph Configuration
# =============================================================================
pve_ceph_enabled: true
ceph_release: reef
pve_ceph_repository_line: "deb http://download.proxmox.com/debian/ceph-reef bookworm main"
pve_ceph_network: "{{ public_network }}"
pve_ceph_cluster_network: "{{ cluster_network }}"

# Server type: ${var.server_type}
# OSDs per node: ${length(local.ceph_osd_disks)}
# Total OSDs: ${local.total_osds}

pve_ceph_osds: ${jsonencode(local.ceph_osd_disks)}

pve_ceph_pools:
  - name: ceph-pool
    pgs: ${local.total_osds >= 9 ? 128 : (local.total_osds >= 6 ? 64 : 32)}
    rule: replicated_rule
    application: rbd
    storage: true
    size: ${local.ceph_pool_size}
    min_size: ${local.ceph_pool_min_size}

# =============================================================================
# Datacenter Configuration
# =============================================================================
pve_datacenter_cfg:
  keyboard: fr
  console: html5

# =============================================================================
# Public Gateway (IPAM Mode)
# =============================================================================
%{if var.enable_public_gateway~}
public_gateway:
  enabled: true
  ip: "${scaleway_vpc_public_gateway_ip.main[0].address}"
  bastion_enabled: ${var.enable_ssh_bastion}
  bastion_port: ${var.bastion_port}
  # Note: DHCP is managed by Scaleway IPAM on the Private Network
  # VMs will receive IPs from the subnet: ${var.public_network_subnet}
%{else~}
public_gateway:
  enabled: false
%{endif~}
EOF

  lifecycle {
    ignore_changes = [content]
  }
}

# =============================================================================
# Hosts File Entries (for reference)
# =============================================================================

resource "local_file" "hosts_entries" {
  count = var.generate_inventory ? 1 : 0
  
  depends_on = [scaleway_baremetal_server.nodes]

  filename = "${path.root}/../config/hosts.generated"
  content  = <<-EOF
# Generated by Terraform - ${timestamp()}
# Add these entries to /etc/hosts on each node (handled by Ansible)

# Proxmox Cluster Nodes - Public Network (vmbr1)
%{for i, ip in local.public_ips~}
${ip} ${local.node_names[i]} ${replace(local.node_names[i], "${var.cluster_name}-", "")}
%{endfor~}

# Proxmox Cluster Nodes - Cluster Network (vmbr2)
%{for i, ip in local.cluster_ips~}
${ip} ${replace(local.node_names[i], "${var.cluster_name}-", "")}-cluster
%{endfor~}

%{if var.enable_qdevice~}
# QDevice
${var.qdevice_ip} ${var.cluster_name}-qdevice qdevice
%{endif~}

%{if var.enable_public_gateway~}
# Public Gateway
${scaleway_vpc_public_gateway_ip.main[0].address} gateway
%{endif~}
EOF

  lifecycle {
    ignore_changes = [content]
  }
}

# =============================================================================
# Environment File
# =============================================================================

resource "local_file" "env_file" {
  count = var.generate_env_file ? 1 : 0

  depends_on = [scaleway_baremetal_server.nodes]

  filename = "${path.root}/../.env"
  content  = <<-EOF
# Generated by Terraform - ${timestamp()}
# Source this file: source .env

# Cluster Configuration
export CLUSTER_NAME="${var.cluster_name}"
export NODE_COUNT=${var.node_count}

# Node Public IPs (Scaleway)
%{for i, ip in local.server_public_ipv4~}
export PVE${i + 1}_PUBLIC_IP="${ip}"
%{endfor~}

# Node Private IPs (Ceph Public Network)
%{for i, ip in local.public_ips~}
export PVE${i + 1}_PRIVATE_IP="${ip}"
%{endfor~}

# First node for quick access
export FIRST_NODE="${local.server_public_ipv4[0]}"
export PROXMOX_URL="https://${local.server_public_ipv4[0]}:8006"

%{if var.enable_public_gateway~}
# Public Gateway
export GATEWAY_IP="${scaleway_vpc_public_gateway_ip.main[0].address}"
export BASTION_PORT="${var.bastion_port}"
export BASTION_CMD="ssh -J bastion@${scaleway_vpc_public_gateway_ip.main[0].address}:${var.bastion_port}"
%{endif~}

# SSH
export SSH_KEY="${var.ssh_private_key_path}"
EOF

  lifecycle {
    ignore_changes = [content]
  }
}
