#!/bin/bash
################################################################################
# Network Configuration Script for Proxmox Ceph HCI
# Generated by Terraform - DO NOT EDIT MANUALLY
################################################################################

set -e

HOSTNAME="${hostname}"
PUBLIC_VLAN="${public_vlan}"
CLUSTER_VLAN="${cluster_vlan}"
PUBLIC_IP="${public_ip}"
PUBLIC_CIDR="${public_cidr}"
CLUSTER_IP="${cluster_ip}"
CLUSTER_CIDR="${cluster_cidr}"

echo "=== Configuring Network for $HOSTNAME ==="
echo "Public VLAN: $PUBLIC_VLAN, IP: $PUBLIC_IP/$PUBLIC_CIDR"
echo "Cluster VLAN: $CLUSTER_VLAN, IP: $CLUSTER_IP/$CLUSTER_CIDR"

# Find the primary network interface (the one with public IP)
PRIMARY_IF=$(ip route | grep default | awk '{print $5}' | head -1)
if [ -z "$PRIMARY_IF" ]; then
    # Fallback: find interface in bridge vmbr0
    PRIMARY_IF=$(ls /sys/class/net/vmbr0/brif/ 2>/dev/null | head -1)
fi
if [ -z "$PRIMARY_IF" ]; then
    # Last resort: find first physical interface
    PRIMARY_IF=$(ip link show | grep -E '^[0-9]+: (enp|eno|eth)' | head -1 | awk -F: '{print $2}' | tr -d ' ')
fi

# If interface is in a bridge, get the bridge port
if [ -d "/sys/class/net/vmbr0/brif" ]; then
    BRIDGE_PORT=$(ls /sys/class/net/vmbr0/brif/ 2>/dev/null | head -1)
    if [ -n "$BRIDGE_PORT" ]; then
        PRIMARY_IF="$BRIDGE_PORT"
    fi
fi

echo "Primary interface: $PRIMARY_IF"

# Backup current network config
cp /etc/network/interfaces /etc/network/interfaces.backup.$(date +%Y%m%d_%H%M%S)

# Create new network configuration
cat > /etc/network/interfaces << EOF
# Network configuration generated by Terraform
# Proxmox Ceph HCI Cluster

auto lo
iface lo inet loopback

# Primary interface (for vmbr0 - public internet)
auto $PRIMARY_IF
iface $PRIMARY_IF inet manual

# Bridge for public internet access (Proxmox default)
auto vmbr0
iface vmbr0 inet dhcp
    bridge-ports $PRIMARY_IF
    bridge-stp off
    bridge-fd 0

# VLAN for Public Private Network (Ceph clients, MON, iSCSI)
auto $PRIMARY_IF.$PUBLIC_VLAN
iface $PRIMARY_IF.$PUBLIC_VLAN inet manual

auto vmbr1
iface vmbr1 inet static
    address $PUBLIC_IP/$PUBLIC_CIDR
    bridge-ports $PRIMARY_IF.$PUBLIC_VLAN
    bridge-stp off
    bridge-fd 0
    bridge-vlan-aware yes
    mtu 9000

# VLAN for Cluster Private Network (OSD replication)
auto $PRIMARY_IF.$CLUSTER_VLAN
iface $PRIMARY_IF.$CLUSTER_VLAN inet manual

auto vmbr2
iface vmbr2 inet static
    address $CLUSTER_IP/$CLUSTER_CIDR
    bridge-ports $PRIMARY_IF.$CLUSTER_VLAN
    bridge-stp off
    bridge-fd 0
    bridge-vlan-aware yes
    mtu 9000
EOF

# Set hostname
hostnamectl set-hostname "$HOSTNAME"

# Update /etc/hosts
cat >> /etc/hosts << EOF

# Proxmox Cluster Nodes - Public Network
${hosts_entries}

# Proxmox Cluster Nodes - Cluster Network
${cluster_hosts}
EOF

echo "=== Applying network configuration ==="

# Create VLAN interfaces
ip link add link $PRIMARY_IF name $PRIMARY_IF.$PUBLIC_VLAN type vlan id $PUBLIC_VLAN 2>/dev/null || true
ip link add link $PRIMARY_IF name $PRIMARY_IF.$CLUSTER_VLAN type vlan id $CLUSTER_VLAN 2>/dev/null || true

# Bring up VLAN interfaces
ip link set $PRIMARY_IF.$PUBLIC_VLAN up 2>/dev/null || true
ip link set $PRIMARY_IF.$CLUSTER_VLAN up 2>/dev/null || true

# Apply full network configuration (will bring up bridges)
ifreload -a 2>/dev/null || systemctl restart networking || true

echo "=== Network configuration complete ==="
ip addr show vmbr1 2>/dev/null || echo "vmbr1 not yet configured"
ip addr show vmbr2 2>/dev/null || echo "vmbr2 not yet configured"

echo "=== Done ==="
